name: Ruby

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '3.4.6' ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby version specified in `.ruby-version`
      with:
        ruby-version: .ruby-version
      uses: ruby/setup-ruby@v1

    - name: Install dependencies
      run:  bundle install --jobs 4 --retry 3

    - name: Run tests with RSpec
      env:
        RAILS_ENV: test
      run: bundle exec rspec

    - name: Run Rubocop
      env:
        RAILS_ENV: test
      run: bundle exec rubocop --config .rubocop.yml
